#
# ===== ChatRange config.yml =====
#

# ========================================
# Contains default formatting for messages and emotes, as well as some command prefixes
# ........................................
# Message and emote contain the default formatting for messages and emotes
# The following placeholders are accepted:
#       - {prefix}          - Range prefix
#       - {range}           - Range name
#       - {player}          - The player that sent the message
#       - {message}         - The message contents
# ========================================
formatting:
  message: '{prefix} {player}: {message}'
  emote: '* {prefix} {player} {message}'
  command:
    ranges:
      message-prefix: 'Available Ranges:'
    spy:
      tag: '[Spy]'
      colour: 'Gray'
      # 'prefix' (default) or 'suffix'
      position: 'prefix'

# ========================================
# ranges - Add your own custom range to the list. Use the following template:
# ........................................
# ranges:
#   <name of range>: The range key, this is used throughout config (default range, ) and in game (ex. mute command) to reference the range .
#     name: Name of the range to be displayed
#     description: Description to be shown for the command
#     command: Command to switch to this range, whitespace characters not allowed
#     aliases: Different command names that can be used to trigger the command
#     distance: Distance of how far can this chat range can reach, decimals allowed.
#                 Leave blank or use negative values for infinite distance.
#     cross-dimension: If this range will work across dimensions/worlds.
#     colour: Colour of the chat in this range
#     format: Format of messages in this range, optional
#                 Leave blank to use default message format
#     prefix: Prefix to be appended before the chat, usually used to denote the range
#     permission: Permission required to run this command, blank if not required
#                 This will be appended after 'chatrange.range.'
#                 Leave blank to ignore.
#     read-permission: Permission required to see messages sent in this range
#                 This will be appended after 'chatrange.read.'
#                 Leave blank to ignore.
# ========================================
ranges:
  local:
    name: 'Local'
    command: 'local'
    description: 'Changes your chat range to Local. [20]'
    aliases:
      - 'l'
    cross-dimension: false
    distance: 20
    colour: 'White'
    prefix: '[Local]'
  admin:
    name: 'Admin'
    command: 'admin'
    description: 'Changes your chat range to Admin.'
    aliases:
      - 'ad'
    cross-dimension: true
    colour: 'Dark Green'
    prefix: '[Admin]'
    permission: 'admin'
    read-permission: 'admin'
  global:
    name: 'Global'
    command: 'global'
    description: 'Changes your chat range to global.'
    aliases:
      - 'g'
    cross-dimension: true
    colour: 'Aqua'
    prefix: '[Global]'
  event:
    name: 'Event'
    command: 'event'
    description: 'Changes your chat range to Event.'
    aliases:
      - 'ev'
    cross-dimension: false
    colour: 'Green'
    prefix: '[Event]'
    permission: 'event'
    format: '{prefix} {message}'

# ========================================
# emotes - Add your own custom emote to the list. Use the following template:
# ........................................
# emotes:
#   <name of emotes>: Name of the emote, this would only be used within this config
#     name: Name of the range to be displayed
#     description: Description to be shown for the command
#     range: Key of range this emote belongs to, must be declared above, case sensitive
#     aliases: Different command names that can be used to trigger the command
#     format: Format of messages in this range, optional
#                 Leave blank to use default message format
#     prefix: Prefix to be appended before the chat, usually to denote the emote
#     permission: Permission required to run this command, blank if not required
#                 This will be appended after 'chatrange.emote.'
# ========================================
emotes:
  local:
    name: 'local'
    description: 'Sends an emote at the Local range.'
    command: 'mel'
    range: 'local'
    aliases:
      - 'emote'
      - 'emotelocal'
    colour: 'Dark Purple'
    prefix: '[Local]'


features:
  # Only sends the current message in the range desired if the alias of the command is used
  alias-single-message: true
  # Notifies the player if there are no recipients for the message sent
  no-recipients-alert: true
  # Using @hand or @offhand will share a snapshot of the item on your hand/offhand to the chat
  display-item-in-chat: true
  # More precise range check using radial distance rather than cube, more expensive
  radial-distance-check: false
  # Number of message recipients will show up in console next to message in format (recievers, hidden recievers, spies)
  recipient-number-logging: true

defaults:
  range: 'global'
  colour:
    message: 'Gold'
    error: 'Red'
    prefix: 'Gray'
    list:
      key: 'Gold'
      value: 'Aqua'

# ========================================
# Contains various messages, can support placeholders. Please check plugin wiki for per message placeholder support.
# ........................................
# Possible placeholderes:
#       - {prefix}          - Relevant range prefix
#       - {range}           - Relevant range anme
#       - {player}          - The player who this is sent to
#       - {message}         - Relevant message
# ========================================
messages:
  message-changed-range: 'Your range has been set to {range}.'
  message-join-range: 'Your range is currently set to {range}.'
  message-chat-no-recipient: 'No players received your message in channel: {range}'
  message-spy-status-on: 'Message spying is currently activated.'
  message-spy-status-off: 'Message spying is currently deactivated.'
  message-spy-on: 'Message spying is now activated.'
  message-spy-off: 'Message spying is now deactivated.'
  message-spy-info: 'You are seeing this message because you are out of range of the sender and have Spy enabled.'
  message-mute-on: 'You have now muted {range}. This will automatically unmute upon the next login.'
  message-mute-off: 'You have now unmuted {range}.'

  error-players-only: 'Sorry, this command can only be used by players.'
  error-player-no-permission: 'Sorry, you do not have the permissions to run this command.'
  error-missing-command-range: 'Sorry, we are unable to find the range for this command.'
  error-retrieving-current-range: 'Sorry, an unexpected error has occurred while trying to retrieve your current range.'
  error-retrieving-ranges: 'Sorry, an unexpected error has occurred while trying to retrieve all of the available ranges.'
  error-missing-command-emote: 'Sorry, we are unable to find the emote for this command.'
  error-missing-message-emote: 'Please include a message for your emote.'
  error-missing-range-mute: 'Please provide the channel you want to mute or unmute.'
  error-item-parsing: 'Sorry, an unexpected error has occurred while trying to format the item.'
  error-mute-unknown-range: 'Sorry, I am unable to find the range ''{range}''.'
